# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '10.0'
  use_frameworks!

  # Pods for MobileChallenge
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'DropDown'

  target 'MobileChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
